[project]
name = "lc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=0.3.23",
    "langchain-mcp-adapters>=0.0.7",
    "langchain-ollama>=0.3.1",
    "langgraph>=0.3.28",
    "notebook>=7.4.0",
]
